### ISSUE TITLE
It is not clearing special characters

### ISSUE THREAD

**Issue by juanbrujo** [afshinpersian/text-to-slug#1]
Using your live demo http://akhgar.net/demo/examples/ I see it is not clearing special characters.
![screen shot 2016-11-02 at 1 13 45 pm](https://cloud.githubusercontent.com/assets/362186/19936991/4cd037a6-a0fe-11e6-81e3-fbf445d1d869.png)

**Comment by afshinakhgar** [comment]
thank you for issuing . I will solve it today

**Comment by afshinakhgar** [comment]
@juanbrujo thank you so much for your comment , I have just fixed it right now. I will be so happy If you chack it out . 

thanks

**Comment by juanbrujo** [comment]
OK it looks now working, but I suggest you should replace the accented characters by the one without the accent.

![screen shot 2016-11-07 at 5 01 57 pm](https://cloud.githubusercontent.com/assets/362186/20073709/0debda74-a50c-11e6-8827-42be01a40a1b.png)

**Comment by afshinakhgar** [comment]
@juanbrujo thank you for your suggestion, I will work on it.
